// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHub;

#nullable disable

namespace SmartHub.Migrations
{
    [DbContext(typeof(SmartHubContext))]
    partial class SmartHubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartHub.Models.PzemEntiy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Current")
                        .HasColumnType("float");

                    b.Property<float>("Energy")
                        .HasColumnType("float");

                    b.Property<float>("Frequency")
                        .HasColumnType("float");

                    b.Property<float>("PF")
                        .HasColumnType("float");

                    b.Property<float>("Power")
                        .HasColumnType("float");

                    b.Property<float>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Pzems", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
